// Generated by cgo from fdw.go. Included here so our functions are
// defined and available.
#include "steampipe_postgres_fdw.h"


// Define our handling functions with Postgres, following the V1 protocol.
//PG_FUNCTION_INFO_V1(steampipe_aws_fdw_handler);
//PG_FUNCTION_INFO_V1(steampipe_aws_fdw_validator);
PG_FUNCTION_INFO_V1(steampipe_fdw_handler);
PG_FUNCTION_INFO_V1(steampipe_fdw_validator);
